---
title: C6312 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 2f33d2a6e7e87f14859614fa25e1bd846764b944
ms.sourcegitcommit: 6cfffa72af599a9d667249caaaa411bb28ea69fd
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 09/02/2020
ms.locfileid: "77273923"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Uyarı C6312: olası sonsuz döngü: try-except için özel durum filtre ifadesinde sabit EXCEPTION_CONTINUE_EXECUTION kullanımı  
  
 Bu uyarı, `EXCEPTION_CONTINUE_EXECUTION` yapılandırılmış bir özel durum işleyicisinin filtre ifadesinde sabit (veya ' i değerlendiren başka bir sabit) kullanımını gösterir. Sabit değerin kullanımı `EXCEPTION_CONTINUE_EXECUTION` sonsuz bir döngüye neden olabilir. Örneğin, donanım tarafından bir özel durum ortaya çıktığında, özel duruma neden olan yönerge yeniden başlatılır. Özel duruma neden olan adres hala bozuksa, başka bir özel durum oluşur ve aynı şekilde işlenir. Bu, sonsuz bir döngüye neden olur.  
  
 İçin açık bir çağrı `RaiseException` sonsuz döngüye doğrudan neden olmaz, ancak korunan bloktaki kodun yürütülmesine devam eder. Bu beklenmeyen bir yol olabilir ve `RaiseException` geçersiz bir işaretçinin başvurusunu kaldırmak için kullanılmışsa sonsuz döngüye neden olabilir.  
  
 Genellikle, `EXCEPTION_CONTINUE_EXECUTION` özel duruma veya temeldeki belleğe neden olan işaretçiyi çözme şansı olan Filter ifadesinde çağrılan bir işlev tarafından döndürülmelidir.  
  
## <a name="example"></a>Örnek  
 Aşağıdaki kod bu uyarıyı oluşturur:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Bu uyarıyı düzeltmek için aşağıdaki kodu kullanın:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```
